import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

import {
  InstantSearch,
  Breadcrumb,
  Configure,
  ClearRefinements,
  CurrentRefinements,
  DynamicWidgets,
  HierarchicalMenu,
  Highlight,
  Hits,
  HitsPerPage,
  InfiniteHits,
  Menu,
  Pagination,
  RangeInput,
  RefinementList,
  PoweredBy,
  SearchBox,
  SortBy,
  ToggleRefinement,
} from 'react-instantsearch-hooks-web';

import { make_client } from 'postgres-searchbox/client';
// During postgres-searchbox development this can be:
// import { make_client } from '../../../package/build/client';

const client = make_client('api/search', {
  highlightColumns: ['primarytitle', 'genres', 'titletype'],
});

function Hit({ hit }: { hit: any }) {
  return (
    <article>
      <Highlight hit={hit} attribute="primarytitle" className="Hit-label" />
      <p>
        {hit.titletype}, {hit.startyear}, {hit.runtimeminutes} min
      </p>
      <p>{hit.genres}</p>
    </article>
  );
}

export default function Basic() {
  return (
    <>
      <Head>
        <title>Postgres Searchbox - With NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InstantSearch
        searchClient={client}
        indexName="postgres_searchbox_movies"
      >
        <div className="Container">
          <div>Left column</div>
          <div className="Search">
            <SearchBox placeholder="Search" autoFocus />

            <div className="Search-header">
              <PoweredBy />
              <HitsPerPage
                items={[
                  { label: '20 hits per page', value: 20, default: true },
                  { label: '40 hits per page', value: 40 },
                ]}
              />
              <SortBy
                items={[
                  { label: 'Relevance', value: 'postgres_searchbox_movies' },
                  {
                    label: 'Title (asc)',
                    value: 'postgres_searchbox_movies?sort=primarytitle',
                  },
                  {
                    label: 'Title (desc)',
                    value: 'postgres_searchbox_movies?sort=primarytitle+desc',
                  },
                  {
                    label: 'Start year (asc)',
                    value: 'postgres_searchbox_movies?sort=startyear+asc',
                  },
                  {
                    label: 'Start year (desc)',
                    value:
                      'postgres_searchbox_movies?sort=startyear+desc+nulls+last',
                  },
                ]}
              />
              {/* <Refresh /> */}
            </div>

            <InfiniteHits hitComponent={Hit} />
            <Pagination className="Pagination" />
          </div>
        </div>
      </InstantSearch>
    </>
  );
}
