import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

import {
  InstantSearch,
  SearchBox,
  Hits,
  Pagination,
} from 'react-instantsearch-hooks-web';

// During postgres-searchbar development this can be:
import { make_client } from '../../../package/build/client';
// Otherwize you should use:
// import { make_client } from 'postgres-searchbox/client';

const inter = Inter({ subsets: ['latin'] });

const client = make_client('api/search');

function Hit({ hit }: { hit: any }) {
  return (
    <article>
      <h1>{hit.primarytitle}</h1>
      <p>
        {hit.titletype}, {hit.startyear}, {hit.runtimeminutes} min
      </p>
      <p>{hit.genres}</p>
    </article>
  );
}

export default function Basic() {
  return (
    <>
      <Head>
        <title>Postgres Searchbox - With NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Please enter your search terms here:</h1>
          <InstantSearch
            searchClient={client}
            indexName="postgres_searchbox_movies"
          >
            <SearchBox />
            <Hits hitComponent={Hit} />
            <Pagination />
          </InstantSearch>
        </div>
      </main>
    </>
  );
}
